### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TaiTitans** [vietanhdev/minesweeper-in-c#1]
thư viện #include <termios.h> có vấn đề anh ơi

**Comment by vietanhdev** [comment]
Có vấn đề gì bạn nhỉ ?

**Comment by TaiTitans** [comment]
nó không chạy thư viện và báo lỗi trên Dev C++ ạ

**Comment by vietanhdev** [comment]
Cái này mình viết để chạy trên Linux, không support Dev C++  bạn nhé. Mình xin phép đóng issue này.
